version: '3.1'
services:
  app:
    container_name: bda
    image: #<image_name>:<image_tag>
    build: ./
    ports:
      - "8092:8091"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD= #password
      - POSTGRES_USER= #user
      - POSTGRES_DB=applicationcatalogue